"""County-level OTC / LAFT / struck-off source registry - loader, vocabulary
and validation for data/county_source_registry.csv.

Relationship to the other governance data sets (none replaced):

  registry.py            one SourceRecord per VENDOR/PLATFORM this project
                         ingests from or is considering (tx_lgbs, fl_laft_pdfs,
                         ...); legal_status drives the ingestion gate.
  source_catalog.py      the Phase 35 per-county coverage matrices (auction
                         sources, discovery stage).
  THIS MODULE            one row per (state, county, source): what publishes
                         this county's post-sale / struck-off / future-resale
                         inventory, who the source of record is, how it is
                         accessed, whether it has been verified, its
                         governance state and its last observed completeness.

The CSV is GENERATED by scripts/build_county_source_registry.py from the
harvesters' own source CSVs plus the audit's candidate tables; a test
asserts the committed file matches the generator. Edit the generator (or
the harvester CSVs), not the output.

Migration 018 creates the same shape as a table (public.county_source_registry)
for a future in-database registry. It is not applied and nothing writes it
yet; `to_db_rows()` is the bridge.
"""
from __future__ import annotations

import csv
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

from . import states
from .states import STATEWIDE_UNIT, PublishingUnit

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REGISTRY_PATH = REPO_ROOT / "data" / "county_source_registry.csv"

COLUMNS = [
    "state", "county", "source_id", "harvester", "inventory_type", "source_authority",
    "canonical_url", "document_url", "purchase_url", "purchase_url_kind",
    "access_method", "machine_format", "verification_status", "governance_status",
    "last_checked", "completeness_status", "evidence_ref", "notes",
]

# Columns the loader ACCEPTS after COLUMNS but the committed CSV, the
# generator and migration 018 do not carry yet. `publishing_unit` (a
# states.PublishingUnit value; blank = COUNTY, which every current row is)
# lets a future registry describe a parish, borough, municipal or
# statewide publisher without the FL/TX county assumption. Adding it to the
# CSV, the generator and the 018 table is a separate, reviewed change
# (docs/otc-inventory-model.md, "State extensibility").
OPTIONAL_COLUMNS = ["publishing_unit"]


class InventoryType(str, Enum):
    # --- carried by public.properties today (migration 017's check constraint)
    POST_SALE_FIXED_PRICE = "POST_SALE_FIXED_PRICE"      # FL LAFT: purchasable now at a set price
    STRUCK_OFF_HELD_IN_TRUST = "STRUCK_OFF_HELD_IN_TRUST"  # TX: struck off to the taxing units, held in trust
    FUTURE_RESALE = "FUTURE_RESALE"                      # TX: awaiting a future resale process
    # --- model vocabulary only: NOT in the 017 constraint, NOT storable until
    #     a future migration widens it (see docs/otc-inventory-model.md).
    #     They exist so the 50-state audit's inventory classes are named
    #     honestly instead of being forced into an FL/TX label.
    POST_SALE = "POST_SALE"                              # post-sale inventory offered by a unit without a published fixed price / process
    STATE_HELD_TAX_LAND = "STATE_HELD_TAX_LAND"          # forfeited to and sold by a STATE agency (AR/MS/AL/WV pattern)
    ADJUDICATED_PROPERTY = "ADJUDICATED_PROPERTY"        # adjudicated to a parish / municipality (LA pattern)


# Exactly what migration 017's properties_inventory_type_check allows. A row
# whose inventory type is outside this set cannot be written to
# public.properties; OtcRecord.to_properties_row() refuses it.
DB_SUPPORTED_INVENTORY_TYPES = frozenset({
    InventoryType.POST_SALE_FIXED_PRICE.value,
    InventoryType.STRUCK_OFF_HELD_IN_TRUST.value,
    InventoryType.FUTURE_RESALE.value,
})


class SourceAuthority(str, Enum):
    GOVERNMENT_DIRECT = "GOVERNMENT_DIRECT"      # the county/clerk/CAD publishes it on its own site
    GOVERNMENT_PLATFORM = "GOVERNMENT_PLATFORM"  # a platform contracted by the government entity
    VENDOR_COUNSEL = "VENDOR_COUNSEL"            # delinquent-tax counsel publishes for its client units
    VENDOR_AUCTION = "VENDOR_AUCTION"            # an auction platform


class PurchaseUrlKind(str, Enum):
    PURCHASE_INSTRUCTIONS = "purchase_instructions"
    OFFER_FORM = "offer_form"
    BID_FORM = "bid_form"
    APPLICATION_FORM = "application_form"
    ONLINE_PURCHASE = "online_purchase"


class AccessMethod(str, Enum):
    HTTP_GET_PDF = "HTTP_GET_PDF"
    HTTP_GET_HTML = "HTTP_GET_HTML"
    HTTP_POST_FORM = "HTTP_POST_FORM"
    JSON_ENDPOINT = "JSON_ENDPOINT"
    HEADLESS_BROWSER = "HEADLESS_BROWSER"
    VENDOR_API = "VENDOR_API"
    UNKNOWN = "UNKNOWN"
    NONE = "NONE"


class MachineFormat(str, Enum):
    PDF = "PDF"
    HTML_TABLE = "HTML_TABLE"
    HTML_CARDS = "HTML_CARDS"
    JSON = "JSON"
    XLSX = "XLSX"
    DOCX = "DOCX"
    PORTAL = "PORTAL"
    UNKNOWN = "UNKNOWN"
    NONE = "NONE"


class VerificationStatus(str, Enum):
    PRODUCTION_VERIFIED = "PRODUCTION_VERIFIED"              # fetched, parsed, rows synced by a production run
    SEARCH_EVIDENCE_ONLY = "SEARCH_EVIDENCE_ONLY"            # URL/title seen in a search index only
    SOURCE_EXISTS_ACCESS_UNKNOWN = "SOURCE_EXISTS_ACCESS_UNKNOWN"
    HISTORICAL_ONLY = "HISTORICAL_ONLY"
    NOT_FOUND_AFTER_SEARCH = "NOT_FOUND_AFTER_SEARCH"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    BLOCKED_VENDOR_ONLY = "BLOCKED_VENDOR_ONLY"


class GovernanceStatus(str, Enum):
    APPROVED = "APPROVED"
    APPROVED_GRANDFATHERED = "APPROVED_GRANDFATHERED"
    TERMS_NOT_VERIFIED = "TERMS_NOT_VERIFIED"
    LEGAL_REVIEW_REQUIRED = "LEGAL_REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CompletenessStatus(str, Enum):
    COMPLETE = "COMPLETE"
    EMPTY = "EMPTY"
    INCOMPLETE = "INCOMPLETE"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


RUNNABLE_GOVERNANCE = frozenset({GovernanceStatus.APPROVED.value, GovernanceStatus.APPROVED_GRANDFATHERED.value})
BLOCKED_SOURCE_IDS = frozenset({"tx_pbfcm", "tx_mvba", "tx_govease", "tx_ctsa"})


@dataclass(frozen=True)
class CountySourceRow:
    state: str
    county: str
    source_id: str
    harvester: str
    inventory_type: str
    source_authority: str
    canonical_url: str
    document_url: str
    purchase_url: str
    purchase_url_kind: str
    access_method: str
    machine_format: str
    verification_status: str
    governance_status: str
    last_checked: str
    completeness_status: str
    evidence_ref: str
    notes: str
    # Optional (see OPTIONAL_COLUMNS). Blank in the CSV reads as COUNTY.
    publishing_unit: str = PublishingUnit.COUNTY.value

    @property
    def is_production(self) -> bool:
        return self.verification_status == VerificationStatus.PRODUCTION_VERIFIED.value

    @property
    def runnable(self) -> bool:
        """May a harvester/adapter run against this row today? Requires a
        production-verified source, an approved governance state, a named
        harvester and a canonical URL - and never a blocked vendor."""
        return (self.is_production and self.governance_status in RUNNABLE_GOVERNANCE
                and bool(self.harvester) and bool(self.canonical_url)
                and self.source_id not in BLOCKED_SOURCE_IDS)


def _enum_values(enum_cls) -> frozenset[str]:
    return frozenset(e.value for e in enum_cls)


def validate_row(row: CountySourceRow, *, known_counties: dict[str, frozenset[str]] | None = None) -> list[str]:
    """Every problem with one row, as strings. Empty list = valid."""
    problems: list[str] = []
    state_cfg = states.get_state(row.state)
    problems.extend(state_problems_for_row(row))
    unit = row.publishing_unit or PublishingUnit.COUNTY.value
    if unit not in _enum_values(PublishingUnit):
        problems.append(f"publishing_unit {row.publishing_unit!r}")
    elif state_cfg is not None and unit not in state_cfg.publishing_units:
        problems.append(f"publishing_unit {unit!r} is not one {row.state} publishes by")
    if unit == PublishingUnit.STATE.value:
        # A statewide publisher has no county; the row says so explicitly
        # rather than borrowing a county name.
        if row.county != STATEWIDE_UNIT:
            problems.append(f"STATE-level row must use county {STATEWIDE_UNIT!r}, not {row.county!r}")
    else:
        if row.county == STATEWIDE_UNIT:
            problems.append(f"county {STATEWIDE_UNIT!r} requires publishing_unit STATE")
        if known_counties and row.state in known_counties and row.county not in known_counties[row.state]:
            problems.append(f"unknown {row.state} county {row.county!r}")
    optional = {
        "inventory_type": InventoryType, "source_authority": SourceAuthority,
        "purchase_url_kind": PurchaseUrlKind,
    }
    for name, enum_cls in optional.items():
        value = getattr(row, name)
        if value and value not in _enum_values(enum_cls):
            problems.append(f"{name} {value!r}")
    required = {
        "access_method": AccessMethod, "machine_format": MachineFormat,
        "verification_status": VerificationStatus, "governance_status": GovernanceStatus,
        "completeness_status": CompletenessStatus,
    }
    for name, enum_cls in required.items():
        value = getattr(row, name)
        if value not in _enum_values(enum_cls):
            problems.append(f"{name} {value!r}")
    for name in ("canonical_url", "document_url", "purchase_url"):
        value = getattr(row, name)
        if value and not value.startswith("https://"):
            problems.append(f"{name} must be https: {value!r}")
    if row.purchase_url and not row.purchase_url_kind:
        problems.append("purchase_url without purchase_url_kind")
    if row.purchase_url_kind and not row.purchase_url:
        problems.append("purchase_url_kind without purchase_url")
    if row.is_production:
        if not row.harvester:
            problems.append("PRODUCTION_VERIFIED row has no harvester")
        if not row.source_id:
            problems.append("PRODUCTION_VERIFIED row has no source_id")
        if row.governance_status not in RUNNABLE_GOVERNANCE:
            problems.append(f"PRODUCTION_VERIFIED row with governance {row.governance_status!r}")
        # Per-state production inventory rule (states.StateConfig): FL rows
        # are always the statutory fixed-price list; TX rows are struck-off /
        # future-resale / unclassified. Same rule as before, read from the
        # state's configuration instead of an `if state == "FL"`.
        if state_cfg is not None and row.inventory_type not in state_cfg.production_inventory_types:
            allowed = ", ".join(sorted(v or "(blank)" for v in state_cfg.production_inventory_types))
            problems.append(f"{row.state} production row must carry one of: {allowed}")
        if row.inventory_type and row.inventory_type not in DB_SUPPORTED_INVENTORY_TYPES:
            problems.append(f"PRODUCTION_VERIFIED row carries inventory_type {row.inventory_type!r}, which public.properties cannot store yet")
    else:
        if row.harvester:
            problems.append("non-production row names a harvester")
        if row.completeness_status != CompletenessStatus.UNKNOWN.value:
            problems.append("non-production row cannot claim a completeness status")
    if row.source_id in BLOCKED_SOURCE_IDS:
        if row.governance_status != GovernanceStatus.BLOCKED.value or row.canonical_url:
            problems.append("blocked vendor row must be governance BLOCKED with no URL")
    if row.verification_status == VerificationStatus.BLOCKED_VENDOR_ONLY.value and row.governance_status != GovernanceStatus.BLOCKED.value:
        problems.append("BLOCKED_VENDOR_ONLY must be governance BLOCKED")
    if row.governance_status == GovernanceStatus.LEGAL_REVIEW_REQUIRED.value and row.is_production:
        problems.append("LEGAL_REVIEW_REQUIRED cannot be production")
    if not row.last_checked:
        problems.append("last_checked missing")
    if not row.evidence_ref:
        problems.append("evidence_ref missing")
    return problems


def state_problems_for_row(row: CountySourceRow) -> list[str]:
    """The state half of validate_row(): the state must be registered in
    harvesters/governance/states.py. Registration is a reviewed commit;
    there is no way to pass an arbitrary state through here."""
    return states.state_problems(row.state)


def load_registry(path: Path | str = REGISTRY_PATH) -> list[CountySourceRow]:
    """Read a registry CSV. The header must be COLUMNS exactly, optionally
    followed by OPTIONAL_COLUMNS in order (the committed file carries only
    COLUMNS; a fixture may carry `publishing_unit`)."""
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        accepted = (COLUMNS, COLUMNS + OPTIONAL_COLUMNS)
        if reader.fieldnames not in accepted:
            raise ValueError(f"{path}: columns {reader.fieldnames} != {COLUMNS} (+ optional {OPTIONAL_COLUMNS})")
        present = list(reader.fieldnames)
        return [CountySourceRow(**{c: (r.get(c) or "").strip() for c in present}) for r in reader]


def validate_registry(rows: list[CountySourceRow], *, known_counties: dict[str, frozenset[str]] | None = None) -> list[str]:
    problems: list[str] = []
    seen: set[tuple[str, str, str]] = set()
    for i, row in enumerate(rows, 2):
        for p in validate_row(row, known_counties=known_counties):
            problems.append(f"line {i} {row.state}/{row.county}: {p}")
        key = (row.state, row.county, row.source_id or row.canonical_url or "(none)")
        if key in seen:
            problems.append(f"line {i}: duplicate {key}")
        seen.add(key)
    return problems


def production_rows(rows: list[CountySourceRow], state: str | None = None) -> list[CountySourceRow]:
    return [r for r in rows if r.is_production and (state is None or r.state == state)]


def expected_harvest_units(rows: list[CountySourceRow], state: str = "FL") -> list[tuple[str, str]]:
    """(source_id, county) pairs a state's harvesters are expected to cover -
    what scripts/laft_lifecycle.py marks NOT_RUN when absent from the status
    file."""
    return sorted({(r.source_id, r.county) for r in production_rows(rows, state)})


def lookup(rows: list[CountySourceRow], state: str, county: str, source_id: str | None = None) -> CountySourceRow | None:
    for r in rows:
        if r.state == state and r.county == county and (source_id is None or r.source_id == source_id):
            return r
    return None


def to_db_rows(rows: list[CountySourceRow]) -> list[dict]:
    """The migration-018 table shape (nulls for blanks). Not written
    anywhere yet - the bridge for a future, separately authorised load.
    Emits COLUMNS only: the 018 table has no publishing_unit column, so a
    row that is not COUNTY-level cannot be represented there yet and is
    refused rather than silently flattened to a county."""
    out = []
    for r in rows:
        if (r.publishing_unit or PublishingUnit.COUNTY.value) != PublishingUnit.COUNTY.value:
            raise ValueError(f"{r.state}/{r.county}: publishing_unit {r.publishing_unit!r} has no column in migration 018")
        d = {c: (getattr(r, c) or None) for c in COLUMNS}
        out.append(d)
    return out
