"""County-level OTC / LAFT / struck-off source registry - loader, vocabulary
and validation for data/county_source_registry.csv.

Relationship to the other governance data sets (none replaced):

  registry.py            one SourceRecord per VENDOR/PLATFORM this project
                         ingests from or is considering (tx_lgbs, fl_laft_pdfs,
                         ...); legal_status drives the ingestion gate.
  source_catalog.py      the Phase 35 per-county coverage matrices (auction
                         sources, discovery stage).
  THIS MODULE            one row per (state, county, source): what publishes
                         this county's post-sale / struck-off / future-resale
                         inventory, who the source of record is, how it is
                         accessed, whether it has been verified, its
                         governance state and its last observed completeness.

The CSV is GENERATED by scripts/build_county_source_registry.py from the
harvesters' own source CSVs plus the audit's candidate tables; a test
asserts the committed file matches the generator. Edit the generator (or
the harvester CSVs), not the output.

Migration 018 creates the same shape as a table (public.county_source_registry)
for a future in-database registry. It is not applied and nothing writes it
yet; `to_db_rows()` is the bridge.
"""
from __future__ import annotations

import csv
from dataclasses import dataclass
from enum import Enum
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REGISTRY_PATH = REPO_ROOT / "data" / "county_source_registry.csv"

COLUMNS = [
    "state", "county", "source_id", "harvester", "inventory_type", "source_authority",
    "canonical_url", "document_url", "purchase_url", "purchase_url_kind",
    "access_method", "machine_format", "verification_status", "governance_status",
    "last_checked", "completeness_status", "evidence_ref", "notes",
]


class InventoryType(str, Enum):
    POST_SALE_FIXED_PRICE = "POST_SALE_FIXED_PRICE"      # FL LAFT: purchasable now at a set price
    STRUCK_OFF_HELD_IN_TRUST = "STRUCK_OFF_HELD_IN_TRUST"  # TX: struck off to the taxing units, held in trust
    FUTURE_RESALE = "FUTURE_RESALE"                      # TX: awaiting a future resale process


class SourceAuthority(str, Enum):
    GOVERNMENT_DIRECT = "GOVERNMENT_DIRECT"      # the county/clerk/CAD publishes it on its own site
    GOVERNMENT_PLATFORM = "GOVERNMENT_PLATFORM"  # a platform contracted by the government entity
    VENDOR_COUNSEL = "VENDOR_COUNSEL"            # delinquent-tax counsel publishes for its client units
    VENDOR_AUCTION = "VENDOR_AUCTION"            # an auction platform


class PurchaseUrlKind(str, Enum):
    PURCHASE_INSTRUCTIONS = "purchase_instructions"
    OFFER_FORM = "offer_form"
    BID_FORM = "bid_form"
    APPLICATION_FORM = "application_form"
    ONLINE_PURCHASE = "online_purchase"


class AccessMethod(str, Enum):
    HTTP_GET_PDF = "HTTP_GET_PDF"
    HTTP_GET_HTML = "HTTP_GET_HTML"
    HTTP_POST_FORM = "HTTP_POST_FORM"
    JSON_ENDPOINT = "JSON_ENDPOINT"
    HEADLESS_BROWSER = "HEADLESS_BROWSER"
    VENDOR_API = "VENDOR_API"
    UNKNOWN = "UNKNOWN"
    NONE = "NONE"


class MachineFormat(str, Enum):
    PDF = "PDF"
    HTML_TABLE = "HTML_TABLE"
    HTML_CARDS = "HTML_CARDS"
    JSON = "JSON"
    XLSX = "XLSX"
    DOCX = "DOCX"
    PORTAL = "PORTAL"
    UNKNOWN = "UNKNOWN"
    NONE = "NONE"


class VerificationStatus(str, Enum):
    PRODUCTION_VERIFIED = "PRODUCTION_VERIFIED"              # fetched, parsed, rows synced by a production run
    SEARCH_EVIDENCE_ONLY = "SEARCH_EVIDENCE_ONLY"            # URL/title seen in a search index only
    SOURCE_EXISTS_ACCESS_UNKNOWN = "SOURCE_EXISTS_ACCESS_UNKNOWN"
    HISTORICAL_ONLY = "HISTORICAL_ONLY"
    NOT_FOUND_AFTER_SEARCH = "NOT_FOUND_AFTER_SEARCH"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    BLOCKED_VENDOR_ONLY = "BLOCKED_VENDOR_ONLY"


class GovernanceStatus(str, Enum):
    APPROVED = "APPROVED"
    APPROVED_GRANDFATHERED = "APPROVED_GRANDFATHERED"
    TERMS_NOT_VERIFIED = "TERMS_NOT_VERIFIED"
    LEGAL_REVIEW_REQUIRED = "LEGAL_REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CompletenessStatus(str, Enum):
    COMPLETE = "COMPLETE"
    EMPTY = "EMPTY"
    INCOMPLETE = "INCOMPLETE"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


RUNNABLE_GOVERNANCE = frozenset({GovernanceStatus.APPROVED.value, GovernanceStatus.APPROVED_GRANDFATHERED.value})
BLOCKED_SOURCE_IDS = frozenset({"tx_pbfcm", "tx_mvba", "tx_govease", "tx_ctsa"})


@dataclass(frozen=True)
class CountySourceRow:
    state: str
    county: str
    source_id: str
    harvester: str
    inventory_type: str
    source_authority: str
    canonical_url: str
    document_url: str
    purchase_url: str
    purchase_url_kind: str
    access_method: str
    machine_format: str
    verification_status: str
    governance_status: str
    last_checked: str
    completeness_status: str
    evidence_ref: str
    notes: str

    @property
    def is_production(self) -> bool:
        return self.verification_status == VerificationStatus.PRODUCTION_VERIFIED.value

    @property
    def runnable(self) -> bool:
        """May a harvester/adapter run against this row today? Requires a
        production-verified source, an approved governance state, a named
        harvester and a canonical URL - and never a blocked vendor."""
        return (self.is_production and self.governance_status in RUNNABLE_GOVERNANCE
                and bool(self.harvester) and bool(self.canonical_url)
                and self.source_id not in BLOCKED_SOURCE_IDS)


def _enum_values(enum_cls) -> frozenset[str]:
    return frozenset(e.value for e in enum_cls)


def validate_row(row: CountySourceRow, *, known_counties: dict[str, frozenset[str]] | None = None) -> list[str]:
    """Every problem with one row, as strings. Empty list = valid."""
    problems: list[str] = []
    if row.state not in ("FL", "TX"):
        problems.append(f"state {row.state!r}")
    if known_counties and row.state in known_counties and row.county not in known_counties[row.state]:
        problems.append(f"unknown {row.state} county {row.county!r}")
    optional = {
        "inventory_type": InventoryType, "source_authority": SourceAuthority,
        "purchase_url_kind": PurchaseUrlKind,
    }
    for name, enum_cls in optional.items():
        value = getattr(row, name)
        if value and value not in _enum_values(enum_cls):
            problems.append(f"{name} {value!r}")
    required = {
        "access_method": AccessMethod, "machine_format": MachineFormat,
        "verification_status": VerificationStatus, "governance_status": GovernanceStatus,
        "completeness_status": CompletenessStatus,
    }
    for name, enum_cls in required.items():
        value = getattr(row, name)
        if value not in _enum_values(enum_cls):
            problems.append(f"{name} {value!r}")
    for name in ("canonical_url", "document_url", "purchase_url"):
        value = getattr(row, name)
        if value and not value.startswith("https://"):
            problems.append(f"{name} must be https: {value!r}")
    if row.purchase_url and not row.purchase_url_kind:
        problems.append("purchase_url without purchase_url_kind")
    if row.purchase_url_kind and not row.purchase_url:
        problems.append("purchase_url_kind without purchase_url")
    if row.is_production:
        if not row.harvester:
            problems.append("PRODUCTION_VERIFIED row has no harvester")
        if not row.source_id:
            problems.append("PRODUCTION_VERIFIED row has no source_id")
        if row.governance_status not in RUNNABLE_GOVERNANCE:
            problems.append(f"PRODUCTION_VERIFIED row with governance {row.governance_status!r}")
        if row.state == "FL" and row.inventory_type != InventoryType.POST_SALE_FIXED_PRICE.value:
            problems.append("FL production row must be POST_SALE_FIXED_PRICE")
    else:
        if row.harvester:
            problems.append("non-production row names a harvester")
        if row.completeness_status != CompletenessStatus.UNKNOWN.value:
            problems.append("non-production row cannot claim a completeness status")
    if row.source_id in BLOCKED_SOURCE_IDS:
        if row.governance_status != GovernanceStatus.BLOCKED.value or row.canonical_url:
            problems.append("blocked vendor row must be governance BLOCKED with no URL")
    if row.verification_status == VerificationStatus.BLOCKED_VENDOR_ONLY.value and row.governance_status != GovernanceStatus.BLOCKED.value:
        problems.append("BLOCKED_VENDOR_ONLY must be governance BLOCKED")
    if row.governance_status == GovernanceStatus.LEGAL_REVIEW_REQUIRED.value and row.is_production:
        problems.append("LEGAL_REVIEW_REQUIRED cannot be production")
    if not row.last_checked:
        problems.append("last_checked missing")
    if not row.evidence_ref:
        problems.append("evidence_ref missing")
    return problems


def load_registry(path: Path | str = REGISTRY_PATH) -> list[CountySourceRow]:
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames != COLUMNS:
            raise ValueError(f"{path}: columns {reader.fieldnames} != {COLUMNS}")
        return [CountySourceRow(**{c: (r.get(c) or "").strip() for c in COLUMNS}) for r in reader]


def validate_registry(rows: list[CountySourceRow], *, known_counties: dict[str, frozenset[str]] | None = None) -> list[str]:
    problems: list[str] = []
    seen: set[tuple[str, str, str]] = set()
    for i, row in enumerate(rows, 2):
        for p in validate_row(row, known_counties=known_counties):
            problems.append(f"line {i} {row.state}/{row.county}: {p}")
        key = (row.state, row.county, row.source_id or row.canonical_url or "(none)")
        if key in seen:
            problems.append(f"line {i}: duplicate {key}")
        seen.add(key)
    return problems


def production_rows(rows: list[CountySourceRow], state: str | None = None) -> list[CountySourceRow]:
    return [r for r in rows if r.is_production and (state is None or r.state == state)]


def expected_harvest_units(rows: list[CountySourceRow], state: str = "FL") -> list[tuple[str, str]]:
    """(source_id, county) pairs a state's harvesters are expected to cover -
    what scripts/laft_lifecycle.py marks NOT_RUN when absent from the status
    file."""
    return sorted({(r.source_id, r.county) for r in production_rows(rows, state)})


def lookup(rows: list[CountySourceRow], state: str, county: str, source_id: str | None = None) -> CountySourceRow | None:
    for r in rows:
        if r.state == state and r.county == county and (source_id is None or r.source_id == source_id):
            return r
    return None


def to_db_rows(rows: list[CountySourceRow]) -> list[dict]:
    """The migration-018 table shape (nulls for blanks). Not written
    anywhere yet - the bridge for a future, separately authorised load."""
    out = []
    for r in rows:
        d = {c: (getattr(r, c) or None) for c in COLUMNS}
        out.append(d)
    return out
