-- Migration 018: county-level OTC / LAFT / struck-off source registry table.
--
-- STATUS: PROPOSED, NOT APPLIED. Applied by hand by the project owner after
-- review. Independent of every other migration (a new table only). Creates
-- NO rows: the registry's content lives in data/county_source_registry.csv
-- (generated by scripts/build_county_source_registry.py, loaded and
-- validated by harvesters/governance/county_source_registry.py). Loading it
-- into this table is a later, separately authorised step
-- (county_source_registry.to_db_rows() produces the exact row shape).
--
-- WHY: the master LAFT / OTC audit (2026-09-29, section 13) found that
-- "which source publishes county X's inventory, who is the source of
-- record, how is it accessed, has it been verified, what is its governance
-- state, when was it last checked and how complete was it" lived only in
-- four harvester CSVs and two coverage matrices with no shared vocabulary.
-- The CSV + loader give that vocabulary now; this table gives the database
-- a place to answer the same questions without the repository.
--
-- ACCESS: same posture as source_health (016) - RLS on, approved users
-- read, only service_role writes. No row carries property data.

begin;

create table public.county_source_registry (
  id                   uuid primary key default gen_random_uuid(),
  state                text not null
                       constraint county_source_registry_state_check check (state in ('FL', 'TX')),
  county               text not null,
  source_id            text,
  harvester            text,
  inventory_type       text
                       constraint county_source_registry_inventory_type_check
                       check (inventory_type is null or inventory_type in ('POST_SALE_FIXED_PRICE', 'STRUCK_OFF_HELD_IN_TRUST', 'FUTURE_RESALE')),
  source_authority     text
                       constraint county_source_registry_source_authority_check
                       check (source_authority is null or source_authority in ('GOVERNMENT_DIRECT', 'GOVERNMENT_PLATFORM', 'VENDOR_COUNSEL', 'VENDOR_AUCTION')),
  canonical_url        text,
  document_url         text,
  purchase_url         text,
  purchase_url_kind    text
                       constraint county_source_registry_purchase_url_kind_check
                       check (purchase_url_kind is null or purchase_url_kind in ('purchase_instructions', 'offer_form', 'bid_form', 'application_form', 'online_purchase')),
  access_method        text not null
                       constraint county_source_registry_access_method_check
                       check (access_method in ('HTTP_GET_PDF', 'HTTP_GET_HTML', 'HTTP_POST_FORM', 'JSON_ENDPOINT', 'HEADLESS_BROWSER', 'VENDOR_API', 'UNKNOWN', 'NONE')),
  machine_format       text not null
                       constraint county_source_registry_machine_format_check
                       check (machine_format in ('PDF', 'HTML_TABLE', 'HTML_CARDS', 'JSON', 'XLSX', 'DOCX', 'PORTAL', 'UNKNOWN', 'NONE')),
  verification_status  text not null
                       constraint county_source_registry_verification_check
                       check (verification_status in ('PRODUCTION_VERIFIED', 'SEARCH_EVIDENCE_ONLY', 'SOURCE_EXISTS_ACCESS_UNKNOWN', 'HISTORICAL_ONLY', 'NOT_FOUND_AFTER_SEARCH', 'MANUAL_REVIEW_REQUIRED', 'BLOCKED_VENDOR_ONLY')),
  governance_status    text not null
                       constraint county_source_registry_governance_check
                       check (governance_status in ('APPROVED', 'APPROVED_GRANDFATHERED', 'TERMS_NOT_VERIFIED', 'LEGAL_REVIEW_REQUIRED', 'BLOCKED', 'NOT_APPLICABLE')),
  last_checked         date not null,
  completeness_status  text not null default 'UNKNOWN'
                       constraint county_source_registry_completeness_check
                       check (completeness_status in ('COMPLETE', 'EMPTY', 'INCOMPLETE', 'FAILED', 'UNKNOWN')),
  evidence_ref         text not null,
  notes                text,
  updated_at           timestamptz not null default now(),
  -- A production-verified source must name its harvester; a blocked vendor
  -- must never carry a URL a future adapter could pick up.
  constraint county_source_registry_production_has_harvester_check
    check (verification_status <> 'PRODUCTION_VERIFIED' or harvester is not null),
  constraint county_source_registry_blocked_has_no_url_check
    check (governance_status <> 'BLOCKED' or canonical_url is null),
  constraint county_source_registry_purchase_pair_check
    check ((purchase_url is null) = (purchase_url_kind is null))
);

create unique index county_source_registry_identity_idx
  on public.county_source_registry (state, county, coalesce(source_id, ''), coalesce(canonical_url, ''));

comment on table public.county_source_registry is
  'One row per (state, county, source) publishing post-sale / struck-off / future-resale inventory: source of record, access method, verification and governance state, last check, last completeness. Content generated from data/county_source_registry.csv; no property data.';

alter table public.county_source_registry enable row level security;

create policy "county_source_registry: approved read" on public.county_source_registry
  as permissive for select to authenticated
  using (public.is_approved());

revoke all on public.county_source_registry from anon, public;
revoke all on public.county_source_registry from authenticated;
grant select on public.county_source_registry to authenticated;
grant select, insert, update, delete on public.county_source_registry to service_role;

create trigger county_source_registry_touch before update on public.county_source_registry
  for each row execute function public.touch_updated_at();

commit;

-- Rollback:
--   drop table public.county_source_registry;
