#!/usr/bin/env python3
"""Write public/laft-refresh-report.json - per-county governance status for
the Florida 'Lands Available for Taxes' (LAFT) availability sources tracked
in harvesters/sources/inventory.py.

Replaces a dead dependency: a weekly scheduled routine used to republish an
out-of-band claude.ai Artifact that scraped county LAFT PDFs/pages directly
(outside this repository, with no governance, publication gate, or review
status attached). That artifact was deleted; this script gives the routine
a repository-backed replacement instead.

Value-free, like the other scripts/build_*.py generators: source names,
URLs, roles, governance status and the documented review reason - no
parcel, price, acreage, address or owner. A consumer that wants row-level
LAFT availability goes through the governed AVAILABLE ledger / publication
gate (harvesters/sources/available_coverage.py, scripts/enrich_available.py),
never this report.

Re-run after editing data/county_source_registry.csv or anything else that
feeds harvesters/sources/inventory.py; a test
(tests/python/test_laft_refresh_report.py) fails while it is stale.

    python3 scripts/build_laft_refresh_report.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from harvesters.sources import inventory as INV  # noqa: E402

OUT = REPO / "public" / "laft-refresh-report.json"

# The Florida counties named in the dead routine's prompt (trig_01XMfynXjCsxUDtJu4Umsqpw,
# "Weekly Central Florida Tax-Deed Land Check"): four it fetched directly
# (Marion, Pasco, Volusia, Sumter) and eight it could never reach without an
# interactive browser (Hillsborough, Orange, Hendry, Osceola, Polk, Hernando,
# Lake, Seminole). Listed here, not discovered, so the report is stable and
# reviewable independent of inventory churn.
COUNTIES = (
    "Marion", "Pasco", "Volusia", "Sumter",
    "Hillsborough", "Orange", "Hendry", "Osceola", "Polk", "Hernando", "Lake", "Seminole",
)


def _county_entry(county: str, inv) -> dict:
    sources = [s for s in INV.sources_for("FL", county, inv) if "availability" in s.roles]
    sources.sort(key=lambda s: s.source_id)
    return {
        "county": county,
        "source_count": len(sources),
        "sources": [
            {
                "source_id": s.source_id, "name": s.name, "publisher": s.publisher,
                "source_type": s.source_type, "url": s.url, "governance": s.governance,
                "governance_reason": s.governance_reason, "access": s.access,
                "access_note": s.access_note, "last_checked": s.last_checked,
                "next_action": s.next_action,
            }
            for s in sources
        ],
    }


def render() -> str:
    inv = INV.build_inventory()
    doc = {
        "note": "Generated by scripts/build_laft_refresh_report.py. Per-county governance status for the FL "
                "LAFT availability sources this report covers - value-free (no parcel, price, acreage, address "
                "or owner). A county with zero sources here has no governed LAFT availability source tracked "
                "yet, not an empty list - see docs/available-inventory.md. This report never bypasses a "
                "publication gate: a REVIEW_REQUIRED or HARD_BLOCKED source is named with its status, never "
                "treated as cleared.",
        "counties": [_county_entry(c, inv) for c in COUNTIES],
    }
    return json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render()
    if a.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("public/laft-refresh-report.json is stale - run scripts/build_laft_refresh_report.py")
            return 1
        print("public/laft-refresh-report.json is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(json.loads(text)['counties'])} counties)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
