#!/usr/bin/env python3
"""Write public/acquisition-evidence.json: the county-level VERIFIED
acquisition record for every applicable row of the two evidence tables
(data/purchase_path_evidence.csv, data/purchase_path_evidence_expansion.csv),
built by the purchase-path engine itself (purchase_path_engine.resolve with
an empty row, so only the evidence table / registry can establish a path).

Why it exists: a property row's otc_provenance.acquisition is written by the
lifecycle / runner, but a later adapter sync can replace otc_provenance
wholesale and drop it (3,500 East Baton Rouge rows on 2026-10-04 kept their
purchase_path_type but lost the steps / office / contacts). The frontend
falls back to this file - same source, same county, same path type only -
so the customer still sees the verified county process. Nothing here is
per-parcel; nothing is written to the database.

--check fails if the file is stale."""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))
import purchase_path_engine as PPE  # noqa: E402
from harvesters.governance.county_source_registry import load_registry  # noqa: E402

OUT = REPO / "public" / "acquisition-evidence.json"
TABLES = (REPO / "data" / "purchase_path_evidence.csv", REPO / "data" / "purchase_path_evidence_expansion.csv")


def records() -> list[dict]:
    reg = {(r.state, r.source_id): r for r in load_registry()}
    out: dict[tuple, dict] = {}
    for table in TABLES:
        evidence = PPE.load_evidence(table)
        for e in evidence:
            if not e.applicable:
                continue
            key = (e.state, e.source_id, e.county)
            if key in out:
                continue
            path, _ = PPE.resolve({}, state=e.state, source_id=e.source_id, county=e.county, registry_row=reg.get((e.state, e.source_id)),
                                  evidence=evidence, harvest_date=e.observed_on)
            # Only a path the evidence row itself established (not a registry fallback).
            if path is None or path.path_type != e.path_type or path.observed_on != e.observed_on:
                continue
            rec = {"state": e.state, "source_id": e.source_id, "county": e.county, "path_type": path.path_type}
            rec.update(path.provenance())
            out[key] = rec
    return [out[k] for k in sorted(out)]


def render() -> str:
    return json.dumps({"_comment": "Generated by scripts/build_acquisition_evidence.py from the verified purchase-path evidence "
                       "tables. County-level process records only; never per-parcel.", "records": records()},
                      indent=1, sort_keys=False, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("public/acquisition-evidence.json is stale - run scripts/build_acquisition_evidence.py")
            return 1
        print("public/acquisition-evidence.json is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(records())} records)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
