#!/usr/bin/env python3
"""Write public/source-inventory.json - the unified source inventory
(harvesters/sources) as the Admin source panel reads it.

Value-free: source names, publishers, URLs, roles, governance and access
facts, and the documented reasons / next actions. No property row, no
identifier, no credential. Re-run after editing the registry, the parcel
configs, the evidence tables or data/enrichment_source_catalog.csv; a test
(tests/python/test_available_enrichment_engine.py) fails while it is stale.

    python3 scripts/build_source_inventory.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from harvesters.sources import inventory as INV  # noqa: E402

OUT = REPO / "public" / "source-inventory.json"


def render() -> str:
    inv = INV.build_inventory()
    doc = {"note": "Generated by scripts/build_source_inventory.py from the repository's source records; "
                   "governance is a dimension of a source, not permission to publish.",
           "states": INV.supported_states(), "production_states": INV.production_states(),
           "summary": INV.summary(inv),
           "sources": [s.as_dict() for s in sorted(inv, key=lambda s: (s.state, s.county, s.source_type, s.source_id))]}
    return json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render()
    if a.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("public/source-inventory.json is stale - run scripts/build_source_inventory.py")
            return 1
        print("public/source-inventory.json is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(json.loads(text)['sources'])} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
