#!/usr/bin/env python3
"""Build public/state-rules.json (the customer state-rules page) and
data/state_verification.json (the verification engine's findings).

  python scripts/build_state_rules.py           # write both
  python scripts/build_state_rules.py --check   # exit 1 if either is out of date

Inputs (all repository files, no network):
  data/state_rules.csv, data/state_ledgers.csv         - harvesters/governance/state_rules.py
  data/purchase_path_evidence*.csv                      - verified county procedures (review_state=verified)
  data/county_source_registry.csv, public/app.js, ...   - harvesters/governance/state_verification.py

The page data never invents a rule: statewide and county rows come from the
rules table as recorded, county procedures only from verified evidence rows,
and every unresolved item keeps its status.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from harvesters.governance import state_rules as SR, state_verification as SV, states  # noqa: E402

PAGE = REPO / "public" / "state-rules.json"
FINDINGS = REPO / "data" / "state_verification.json"
EVIDENCE = ("purchase_path_evidence.csv", "purchase_path_evidence_expansion.csv")
PROC_FIELDS = ("county", "source_id", "path_type", "source_title", "evidence_url", "observed_on", "instructions", "steps",
               "office", "evidence")


def county_procedures() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for name in EVIDENCE:
        with open(REPO / "data" / name, newline="", encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                if (r.get("review_state") or "").strip() != "verified" or not (r.get("evidence_url") or "").startswith("https://"):
                    continue
                rec = {k: (r.get(k) or "").strip() for k in PROC_FIELDS if (r.get(k) or "").strip()}
                out.setdefault(r["state"], []).append(rec)
    for st in out:
        out[st].sort(key=lambda x: (x.get("county", ""), x.get("source_id", "")))
    return out


def build_page() -> dict:
    rules, ledgers = SR.load_rules(), SR.load_ledgers()
    procs = county_procedures()
    doc = {
        "_comment": "Generated by scripts/build_state_rules.py from data/state_rules.csv, data/state_ledgers.csv and the "
                    "verified evidence tables. Do not edit.",
        "kinds": SR.KIND_LABELS, "statuses": SR.STATUS_LABELS, "ledger_statuses": SR.LEDGER_STATUS_LABELS,
        "eligibilities": SR.ELIGIBILITY_LABELS,
        "states": {},
    }
    history = SR.load_history()
    for st in sorted(states.PRODUCTION_STATES):
        cfg = states.get_state(st)
        mine = [r for r in rules if r.state == st]
        doc["states"][st] = {
            "name": cfg.name if cfg else st,
            # Eligibility (does the product exist here), tracking (does TAXACQ
            # read a source for it) and county coverage (which counties, from
            # which sources / verified procedures) - all apart from any count.
            "ledgers": {l.ledger: {**{k: v for k, v in l.as_dict().items() if k not in ("state", "ledger")},
                                   "coverage": SV.county_coverage(st, l.ledger, rules=mine)}
                        for l in ledgers if l.state == st},
            "rules": [r.as_dict() for r in mine if not r.county],
            "county_rules": [r.as_dict() for r in mine if r.county],
            "county_procedures": procs.get(st, []),
            "history": [{"county": h.county, "topic": h.topic, "version": h.version, "changed_on": h.changed_on,
                         "change": h.change, "prior_status": h.prior_status, "prior_statement": h.prior_statement,
                         "affects": h.affects} for h in history if h.state == st],
        }
    return doc


def build() -> tuple[dict, dict]:
    page = build_page()
    findings = SV.run(rules_json=page)
    page_out = dict(page)
    page_out["verification"] = {st: {"by_status": findings["by_state"].get(st, {}),
                                     "findings": [f for f in findings["findings"] if f["state"] == st]}
                                for st in page["states"]}
    return page_out, findings


def _dump(obj) -> str:
    return json.dumps(obj, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    problems = SR.validate()
    if problems:
        print("state rules invalid:\n  " + "\n  ".join(problems), file=sys.stderr)
        return 1
    page, findings = build()
    want = {PAGE: _dump(page), FINDINGS: _dump(findings)}
    if a.check:
        stale = [p for p, text in want.items() if not p.is_file() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"{p.relative_to(REPO)} is out of date - rerun scripts/build_state_rules.py", file=sys.stderr)
        return 1 if stale else 0
    for p, text in want.items():
        p.write_text(text, encoding="utf-8")
    s = findings["summary"]
    print(f"wrote {PAGE.relative_to(REPO)} ({len(page['states'])} states) and {FINDINGS.relative_to(REPO)}: "
          + ", ".join(f"{k} {v}" for k, v in s.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
