#!/usr/bin/env python3
"""Build the market-test report and the market-test county list.

  docs/market-test-report.md       every market's metrics, tier, failed rules,
                                   visibility and the shortlist (generated)
  data/market_test_counties.csv    the counties of the strongest markets that
                                   name their counties (enrichment rule P5)

From data/market_audit_snapshot.json, data/market_caveats.csv and
public/acquisition-evidence.json (harvesters/sources/market_metrics.py).
--check exits 1 when either file is not current. No network, no database.
"""
from __future__ import annotations

import argparse
import csv
import io
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from harvesters.sources import market_metrics as MM  # noqa: E402

REPORT = REPO / "docs" / "market-test-report.md"
COUNTIES = REPO / "data" / "market_test_counties.csv"


def _fmt(n) -> str:
    return f"{n:,}" if isinstance(n, int) else f"{n:.0f}%"


def _why(m: MM.Market) -> str:
    """Only what the metrics say - never a claim about demand or profit."""
    x = m.metrics()
    parts = [f"{x['visible']:,} customer-visible records in {x['counties']} {'county' if x['counties'] == 1 else 'counties'}"]
    parts.append(f"{x['path_pct']:.0f}% carry the published path ({x['path_metric'].replace('_', ' ')})")
    parts.append(f"{x['coordinates_pct']:.0f}% imagery-capable coordinates")
    return "; ".join(parts)


def _missing(m: MM.Market) -> str:
    x = m.metrics()
    gaps = [MM.RULE_LABELS[f] for f in m.failed if f in MM.RULE_LABELS]
    for key, label in (("authoritative_coordinates_pct", "authoritative coordinates"), ("legal_description_pct", "legal descriptions"),
                       ("taxable_value_pct", "taxable values"), ("acreage_pct", "acreage"), ("land_use_pct", "land use")):
        if x[key] < 80:
            gaps.append(f"{label} {x[key]:.0f}%")
    for c in m.caveats:
        if c["kind"] == "gap":
            gaps.append(c["note"])
    return "; ".join(gaps) or "nothing measured as missing"


def render(ms: list[MM.Market], snapshot: dict) -> str:
    sl = MM.shortlist(ms)
    out = io.StringIO()
    w = out.write
    w("# Market-test report (generated)\n\n")
    w("Generated by `scripts/build_market_report.py` from `data/market_audit_snapshot.json` "
      f"(counts measured read-only in production on {snapshot['measured_on']}), `data/market_caveats.csv` and "
      "`public/acquisition-evidence.json`. Do not edit by hand; rebuild after changing any of them.\n\n")
    w("Rules (`harvesters/sources/market_metrics.py`), no score:\n\n")
    w("* **HELD** - no customer-visible record (the source is not cleared for customers). Kept for admins.\n")
    w("* **NOT_CURRENT** - visible, but the inventory is a finished sale.\n")
    w(f"* **FOCUS** - visible and every rule holds: identity >= {MM.THRESHOLDS['identity']:.0%}, coordinates >= "
      f"{MM.THRESHOLDS['coordinates']:.0%}, published path >= {MM.THRESHOLDS['path']:.0%} (auction URL for auctions; "
      "the certificate sale page or acquisition evidence for liens; verified acquisition evidence for Available), and "
      "no freshness / dated-list / source-review caveat.\n")
    w("* **BROWSE** - visible, at least one rule fails (named below).\n\n")
    w("Shortlist order: FOCUS by visible records, then BROWSE by number of failed rules and visible records. "
      "Raw size never promotes a market past a failed rule; NOT_CURRENT and HELD markets are not prioritized.\n\n")
    w("Percentages are of active records. Imagery-capable = coordinates (the live USDA NAIP view needs nothing else). "
      "Activation is NOT implied by any list here.\n\n")
    w("## All markets\n\n")
    w("| Market | Tier | Failed rules | Active | Visible | Counties | Identity | Coords | Authoritative coords | Path | Legal | Value | Taxable | Acreage | Land use | Stored imagery |\n")
    w("|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    for m in sorted(ms, key=lambda m: (MM.TIERS.index(m.tier), -m.visible, -int(m.unit["active"]), m.name)):
        x = m.metrics()
        w(f"| {m.name} | {m.tier} | {', '.join(m.failed) or '-'} | {x['active']:,} | {x['visible']:,} | {x['counties']} | "
          f"{x['identity_pct']:.0f}% | {x['coordinates_pct']:.0f}% | {x['authoritative_coordinates_pct']:.0f}% | "
          f"{x['path_pct']:.0f}% | {x['legal_description_pct']:.0f}% | {x['assessed_value_pct']:.0f}% | "
          f"{x['taxable_value_pct']:.0f}% | {x['acreage_pct']:.0f}% | {x['land_use_pct']:.0f}% | {x['stored_imagery_pct']:.0f}% |\n")
    for title, key in (("Strongest test markets", "strongest"), ("Secondary markets", "secondary"),
                       ("Not prioritized yet", "not_prioritized"), ("Also not prioritized", "also_not_prioritized")):
        w(f"\n## {title}\n\n")
        if not sl[key]:
            w("None.\n")
            continue
        for i, m in enumerate(sl[key], 1):
            x = m.metrics()
            w(f"### {i}. {m.name} ({m.tier})\n\n")
            names = ", ".join(m.unit.get("county_names") or []) or f"{x['counties']} counties (statewide sources)"
            w(f"* **Counties:** {names}\n")
            w(f"* **Ledger:** {m.ledger}\n")
            w(f"* **Usable inventory:** {x['visible']:,} customer-visible of {x['active']:,} active\n")
            w(f"* **Published path:** {x['path_pct']:.0f}% ({x['path_metric'].replace('_', ' ')})"
              + (f"; {x['verified_acquisition_counties']} {'county' if x['verified_acquisition_counties'] == 1 else 'counties'} with a verified acquisition record" if m.ledger == "AVAILABLE" else "") + "\n")
            w(f"* **Property data:** legal {x['legal_description_pct']:.0f}%, value {x['assessed_value_pct']:.0f}%, taxable "
              f"{x['taxable_value_pct']:.0f}%, acreage {x['acreage_pct']:.0f}%, land use {x['land_use_pct']:.0f}%\n")
            w(f"* **Coordinates:** {x['coordinates_pct']:.0f}% ({x['authoritative_coordinates_pct']:.0f}% authoritative)\n")
            w(f"* **Imagery:** {x['imagery_capable_pct']:.0f}% imagery-capable, {x['stored_imagery_pct']:.0f}% stored\n")
            w(f"* **Sources:** {'; '.join(m.unit.get('sources') or [])}\n")
            w(f"* **Source status / restrictions:** " + ("; ".join(c["note"] for c in m.caveats) or "no documented caveat") + "\n")
            listed = key == "strongest" and m.unit.get("county_names")
            w(f"* **Visibility:** {MM.visibility(m)}"
              + ("; its counties are listed for market testing (data/market_test_counties.csv, enrichment rule P5)" if listed else "")
              + "\n")
            w(f"* **Why it is interesting (measured):** {_why(m)}\n")
            w(f"* **Missing:** {_missing(m)}\n\n")
    return out.getvalue()


def counties_csv(ms: list[MM.Market]) -> str:
    out = io.StringIO()
    wr = csv.writer(out, lineterminator="\n")
    wr.writerow(["state", "county", "ledger", "reason"])
    for m in MM.shortlist(ms)["strongest"]:
        for c in m.unit.get("county_names") or []:
            wr.writerow([m.state, c, m.ledger, f"strongest test market ({m.tier})"])
    return out.getvalue()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    snap = MM.load_snapshot()
    ms = MM.markets(snap)
    want = {REPORT: render(ms, snap), COUNTIES: counties_csv(ms)}
    if a.check:
        stale = [p for p, t in want.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print(f"{p.relative_to(REPO)} is not current - run scripts/build_market_report.py")
        if not stale:
            print("market report and market-test counties are current")
        return 1 if stale else 0
    for p, t in want.items():
        p.write_text(t, encoding="utf-8")
        print(f"wrote {p.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
