#!/usr/bin/env python3
"""Write public/available-coverage.json - per supported state, WHY its
AVAILABLE ledger shows what it does (harvesters/sources/available_coverage).

Value-free: source names, counties, URLs, governance / access states and the
documented research. No property row, identifier or credential. The AVAILABLE
empty state reads it so a zero says which zero it is. Re-run after editing the
registry, data/enrichment_source_catalog.csv, data/available_discovery_pages.csv
or data/available_state_research.csv; a test fails while it is stale.

    python3 scripts/build_available_coverage.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
from harvesters.sources import available_coverage as AC  # noqa: E402

OUT = REPO / "public" / "available-coverage.json"


def render() -> str:
    doc = {"note": "Generated by scripts/build_available_coverage.py. Why each supported state's AVAILABLE ledger "
                   "shows what it does; a candidate is never a source of rows until it is captured, reviewed and "
                   "harvested.",
           "statuses": list(AC.STATUSES), "states": AC.coverage()}
    return json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    problems = AC.problems()
    if problems:
        print("\n".join(problems))
        return 1
    text = render()
    if a.check:
        if (OUT.read_text(encoding="utf-8") if OUT.exists() else "") != text:
            print("public/available-coverage.json is stale - run scripts/build_available_coverage.py")
            return 1
        print("public/available-coverage.json is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(json.loads(text)['states'])} states)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
