#!/usr/bin/env python3
"""Render the current-state coverage matrix (state x ledger) from a
counts-only snapshot.

  python scripts/current_state_report.py --snapshot data/current_state/coverage-2026-10-10.json \
      --out docs/current-state-coverage.md [--check]

The snapshot is the JSON result of scripts/sql/current_state_coverage.sql
(read-only, counts only) plus `measured_at` / `evidence` /
`baseline_commit`. Nothing here reaches the network or a database, and no
row value is ever printed - only counts and shares. --check compares the
rendered text with --out (a test pins the committed file).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

LEDGER = {"auction": "Auctions", "laft": "Available", "certificate": "Liens & Certificates"}
COLUMNS = (("act_parcel", "Parcel #"), ("act_coords", "Coordinates"), ("act_assessed", "Assessed value"),
           ("act_landuse", "Land use"), ("act_flood", "Flood zone"), ("act_url", "Source link"),
           ("act_prov", "Field provenance"))


def pct(n: int, d: int) -> str:
    return "-" if not d else f"{n} ({round(100 * n / d)}%)"


def freshness(r: dict) -> str:
    """Counts-only freshness of a state x ledger: how many active rows were
    read within 36 h. Never a verdict on the source's own cadence - that is
    unit_freshness / source health's job (per source, per county)."""
    a = r["active"]
    if not a:
        return "no active rows"
    fresh = a - r["act_never_seen"] - r["act_seen_gt36h"]
    return f"{fresh} of {a} read ≤36 h" + (f"; {r['act_never_seen']} never stamped" if r["act_never_seen"] else "")


def render(snap: dict) -> str:
    rows = sorted(snap["rows"], key=lambda r: (r["state"], r["source"]))
    out = [
        "# Current-state coverage matrix",
        "",
        f"Measured {snap['measured_at']} · {snap['evidence']} · repository at `{snap['baseline_commit'][:7]}`.",
        "Generated by `scripts/current_state_report.py` - do not edit by hand.",
        "",
        "\"Active\" = status active / available / scheduled and not delisted. Every share below is of the active rows.",
        "",
        "| State | Ledger | Rows | Active | " + " | ".join(h for _, h in COLUMNS) + " | Past sale date | Freshness |",
        "|---|---|---|---|" + "---|" * len(COLUMNS) + "---|---|",
    ]
    for r in rows:
        a = r["active"]
        cells = [pct(r[k], a) for k, _ in COLUMNS]
        past = str(r["act_past_sale"]) if r["source"] == "auction" else "n/a"
        out.append(f"| {r['state']} | {LEDGER.get(r['source'], r['source'])} | {r['total']} | {a} | "
                   + " | ".join(cells) + f" | {past} | {freshness(r)} |")
    tot = {k: sum(r[k] for r in rows) for k in ("total", "active", "act_never_seen", "act_seen_gt36h")}
    out += ["", f"Totals: {tot['total']} rows, {tot['active']} active; "
                f"{tot['active'] - tot['act_never_seen'] - tot['act_seen_gt36h']} active rows read within 36 h, "
                f"{tot['act_seen_gt36h']} older, {tot['act_never_seen']} never stamped."]
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--snapshot", required=True)
    ap.add_argument("--out")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render(json.loads(Path(a.snapshot).read_text(encoding="utf-8")))
    if a.check:
        if not a.out or not Path(a.out).exists() or Path(a.out).read_text(encoding="utf-8") != text:
            print(f"{a.out} is out of date - rerun without --check", file=sys.stderr)
            return 1
        return 0
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
