#!/usr/bin/env python3
"""Render the source-quality matrix (state x source x ledger, with each
county's own row) from a counts-only snapshot.

  python scripts/source_quality_report.py --snapshot data/current_state/source-quality-2026-10-10.json \
      --out docs/source-quality-matrix.md [--check]

The snapshot is the JSON result of scripts/sql/source_quality_matrix.sql
(read-only, counts only) plus `measured_at` / `evidence` /
`baseline_commit`. Every cell is "n/N" - the count over that row's active
rows - so a share is never shown without its denominator. Nothing here
reaches a network or a database, and no row value is ever printed. --check
compares the rendered text with --out (a test pins the committed file).
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

LEDGER = {"auction": "Auctions", "laft": "Available", "certificate": "Liens & Certificates"}
# (snapshot key, column header). Coverage: higher is better.
COVERAGE = (("parcel", "Parcel"), ("coords", "Coordinates"), ("flood_checked", "Flood checked"),
            ("amount", "Amount published"), ("source_link", "Source link"), ("list_as_of", "List date"),
            ("path_typed", "Acquisition path typed"), ("provenance", "Field provenance"))
# Defects: any non-zero count is a finding (or an explained characteristic).
DEFECTS = (("never_seen", "Never read"), ("seen_gt36h", "Read >36 h ago"), ("past_sale", "Past sale date"),
           ("parcel_no_digit", "Parcel without a digit"), ("dup_parcel", "Repeated parcel value"),
           ("bid_amount_mismatch", "Bid ≠ amount"), ("link_not_https", "Link not https"),
           ("list_as_of_future", "List date in the future"), ("seen_order_bad", "First seen after last seen"))
SUMS = tuple(k for k, _ in COVERAGE) + tuple(k for k, _ in DEFECTS) + ("active",)


def frac(n: int, d: int) -> str:
    return "-" if not d else f"{n}/{d}"


def by_source(rows: list[dict]) -> list[dict]:
    """One aggregate per (state, source_id, ledger): sums over its counties."""
    agg: dict[tuple, dict] = defaultdict(lambda: {k: 0 for k in SUMS} | {"counties": 0, "publication": set()})
    for r in rows:
        a = agg[(r["state"], r["source_id"], r["ledger"])]
        for k in SUMS:
            a[k] += int(r.get(k) or 0)
        a["counties"] += 1
        a["publication"].update(str(r.get("publication") or "NULL").split("|"))
    out = []
    for (state, sid, ledger), a in sorted(agg.items()):
        out.append({"state": state, "source_id": sid, "ledger": ledger, **{k: a[k] for k in SUMS},
                    "counties": a["counties"], "publication": "|".join(sorted(a["publication"]))})
    return out


def render(snap: dict) -> str:
    rows = snap["rows"]
    srcs = by_source(rows)
    out = [
        "# Source-quality matrix",
        "",
        f"Measured {snap['measured_at']} · {snap['evidence']} · repository at `{snap['baseline_commit'][:7]}`.",
        "Generated by `scripts/source_quality_report.py` - do not edit by hand.",
        "",
        "Active rows only (status active / available / scheduled, not delisted). Every cell is a count over that row's",
        "active rows (`n/N`). Publication is the source's own customer-publication status on the rows - never a",
        "statement about the property.",
        "",
        "## By source",
        "",
        "| State | Source | Ledger | Counties | Active | " + " | ".join(h for _, h in COVERAGE) + " | Publication |",
        "|---|---|---|---|---|" + "---|" * len(COVERAGE) + "---|",
    ]
    for s in srcs:
        a = s["active"]
        out.append(f"| {s['state']} | `{s['source_id']}` | {LEDGER.get(s['ledger'], s['ledger'])} | {s['counties']} | {a} | "
                   + " | ".join(frac(s[k], a) for k, _ in COVERAGE) + f" | {s['publication']} |")
    out += ["", "## Defect counts by source", "",
            "| State | Source | Ledger | Active | " + " | ".join(h for _, h in DEFECTS) + " |",
            "|---|---|---|---|" + "---|" * len(DEFECTS)]
    for s in srcs:
        a = s["active"]
        out.append(f"| {s['state']} | `{s['source_id']}` | {LEDGER.get(s['ledger'], s['ledger'])} | {a} | "
                   + " | ".join(frac(s[k], a) if s[k] else "0" for k, _ in DEFECTS) + " |")
    out += ["", "## By county", "",
            "| State | County | Source | Ledger | Active | " + " | ".join(h for _, h in COVERAGE)
            + " | Never read | Read >36 h ago | Last read |",
            "|---|---|---|---|---|" + "---|" * len(COVERAGE) + "---|---|---|"]
    for r in sorted(rows, key=lambda r: (r["state"], r["source_id"], r["county"], r["ledger"])):
        a = int(r["active"])
        last = str(r.get("last_seen_max") or "never")[:16]
        out.append(f"| {r['state']} | {r['county']} | `{r['source_id']}` | {LEDGER.get(r['ledger'], r['ledger'])} | {a} | "
                   + " | ".join(frac(int(r.get(k) or 0), a) for k, _ in COVERAGE)
                   + f" | {frac(int(r['never_seen']), a)} | {frac(int(r['seen_gt36h']), a)} | {last} |")
    tot = {k: sum(s[k] for s in srcs) for k in SUMS}
    out += ["", f"Totals: {tot['active']} active rows across {len(srcs)} source/ledger pairs and {len(rows)} county units; "
                f"{tot['active'] - tot['never_seen'] - tot['seen_gt36h']}/{tot['active']} read within 36 h, "
                f"{tot['coords']}/{tot['active']} with coordinates, {tot['flood_checked']}/{tot['active']} flood-checked."]
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--snapshot", required=True)
    ap.add_argument("--out")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = render(json.loads(Path(a.snapshot).read_text(encoding="utf-8")))
    if a.check:
        if not a.out or not Path(a.out).exists() or Path(a.out).read_text(encoding="utf-8") != text:
            print(f"{a.out} is out of date - rerun without --check", file=sys.stderr)
            return 1
        return 0
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
